/**
 * Home-screen widget (WG2, ADR-0011) — Android only in this batch (iOS
 * widget deferred: owner runs Android, no Apple Team ID on file).
 *
 * Build-time config plugin, zero runtime dependency (same pattern as
 * `with-app-shortcuts`): three buttons (Suara / Tambah / Pindai) fire plain
 * `VIEW` intents at deep links the app already owns, plus `source=widget`
 * so the form arms the widget save path (local notification + dismiss).
 * The widget holds no data, no session, no query — `updatePeriodMillis` is
 * 0 and there is deliberately no `configure` activity or refresh logic.
 *
 * Like the shortcuts plugin, this takes effect on the next preview rebuild
 * (lesson D4/B4), never via OTA.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import {
  withAndroidManifest,
  withDangerousMod,
  type ConfigPlugin,
} from 'expo/config-plugins';

const WIDGET_INFO_XML = 'cashtrix_widget_info';
const WIDGET_LAYOUT_XML = 'cashtrix_widget';
const WIDGET_STRINGS_XML = 'cashtrix_widget_strings';

type WidgetButton = {
  viewId: string;
  labelKey: string;
  label: string;
  description: string;
  uri: string;
};

const BUTTONS: WidgetButton[] = [
  {
    viewId: 'widget_voice',
    labelKey: 'widget_voice',
    label: 'Catat Suara',
    description: 'Catat dengan suara',
    uri: 'cashtrix://voice?source=widget',
  },
  {
    viewId: 'widget_add',
    labelKey: 'widget_add',
    label: 'Tambah',
    description: 'Tambah transaksi',
    uri: 'cashtrix://add-transaction?source=widget',
  },
  {
    viewId: 'widget_scan',
    labelKey: 'widget_scan',
    label: 'Pindai',
    description: 'Pindai struk',
    uri: 'cashtrix://scan?source=widget',
  },
];

function widgetInfoXml(): string {
  return `<?xml version="1.0" encoding="utf-8"?>
<appwidget-provider xmlns:android="http://schemas.android.com/apk/res/android"
  android:minWidth="180dp"
  android:minHeight="48dp"
  android:updatePeriodMillis="0"
  android:initialLayout="@layout/${WIDGET_LAYOUT_XML}"
  android:description="@string/widget_desc"
  android:widgetCategory="home_screen" />
`;
}

function widgetLayoutXml(): string {
  const buttons = BUTTONS.map(
    (button) => `  <Button
    android:id="@+id/${button.viewId}"
    android:layout_width="0dp"
    android:layout_height="wrap_content"
    android:layout_weight="1"
    android:text="@string/${button.labelKey}"
    android:contentDescription="${button.description}"
    android:textColor="#E5E5E5"
    android:background="?android:attr/selectableItemBackground" />`,
  ).join('\n');
  return `<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
  android:layout_width="match_parent"
  android:layout_height="wrap_content"
  android:orientation="horizontal"
  android:gravity="center"
  android:padding="8dp"
  android:background="#1C1C1E">
${buttons}
</LinearLayout>
`;
}

function widgetStringsXml(): string {
  const entries = BUTTONS.map(
    (button) =>
      `  <string name="${button.labelKey}">${button.label}</string>`,
  ).join('\n');
  return `<?xml version="1.0" encoding="utf-8"?>\n<resources>\n${entries}\n  <string name="widget_desc">Pintasan catat Cashtrix</string>\n</resources>\n`;
}

function widgetProviderJava(packageName: string): string {
  const bindings = BUTTONS.map(
    (button) =>
      `    bindButton(context, views, R.id.${button.viewId}, "${button.uri}");`,
  ).join('\n');
  return `package ${packageName};

import android.app.PendingIntent;
import android.appwidget.AppWidgetManager;
import android.appwidget.AppWidgetProvider;
import android.content.Context;
import android.content.Intent;
import android.net.Uri;
import android.widget.RemoteViews;

/** Generated by the WG2 config plugin — buttons only, no data, no session. */
public class CashtrixWidgetProvider extends AppWidgetProvider {
  static void updateWidget(Context context, AppWidgetManager manager, int widgetId) {
    RemoteViews views = new RemoteViews(context.getPackageName(), R.layout.${WIDGET_LAYOUT_XML});
${bindings}
    manager.updateAppWidget(widgetId, views);
  }

  static void bindButton(Context context, RemoteViews views, int viewId, String uri) {
    Intent intent = new Intent(Intent.ACTION_VIEW, Uri.parse(uri));
    intent.setPackage(context.getPackageName());
    PendingIntent pending = PendingIntent.getActivity(
      context, viewId, intent,
      PendingIntent.FLAG_UPDATE_CURRENT | PendingIntent.FLAG_IMMUTABLE);
    views.setOnClickPendingIntent(viewId, pending);
  }

  @Override
  public void onUpdate(Context context, AppWidgetManager manager, int[] widgetIds) {
    for (int widgetId : widgetIds) {
      updateWidget(context, manager, widgetId);
    }
  }
}
`;
}

const withCashtrixAppWidget: ConfigPlugin = (config) => {
  const packageName =
    config.android?.package ?? 'com.callmerev95.cashtrix';

  config = withAndroidManifest(config, (config) => {
    // `receiver` is absent from the manifest activity/application types, so
    // the provider entry is handled through a narrow structural view (same
    // trick as the launcher `meta-data` in `with-app-shortcuts`).
    type ManifestReceiver = {
      $?: { [key: string]: string };
      'intent-filter'?: {
        action?: { $?: { [key: string]: string } }[];
      }[];
      'meta-data'?: {
        $?: { [key: string]: string };
      }[];
    };
    type ManifestApplication = {
      receiver?: ManifestReceiver[];
    };
    const application = config.modResults.manifest.application?.[0] as unknown as
      | ManifestApplication
      | undefined;
    if (application) {
      if (!application.receiver) application.receiver = [];
      const exists = application.receiver.some(
        (item) =>
          item.$?.['android:name'] === '.CashtrixWidgetProvider',
      );
      if (!exists) {
        application.receiver.push({
          $: {
            'android:name': '.CashtrixWidgetProvider',
            'android:exported': 'false',
          },
          'intent-filter': [
            {
              action: [
                {
                  $: {
                    'android:name':
                      'android.appwidget.action.APPWIDGET_UPDATE',
                  },
                },
              ],
            },
          ],
          'meta-data': [
            {
              $: {
                'android:name': 'android.appwidget.provider',
                'android:resource': `@xml/${WIDGET_INFO_XML}`,
              },
            },
          ],
        });
      }
    }
    return config;
  });

  config = withDangerousMod(config, [
    'android',
    async (config) => {
      const resDir = join(
        config.modRequest.platformProjectRoot,
        'app/src/main/res',
      );
      const xmlDir = join(resDir, 'xml');
      const layoutDir = join(resDir, 'layout');
      const valuesDir = join(resDir, 'values');
      mkdirSync(xmlDir, { recursive: true });
      mkdirSync(layoutDir, { recursive: true });
      mkdirSync(valuesDir, { recursive: true });
      writeFileSync(
        join(xmlDir, `${WIDGET_INFO_XML}.xml`),
        widgetInfoXml(),
      );
      writeFileSync(
        join(layoutDir, `${WIDGET_LAYOUT_XML}.xml`),
        widgetLayoutXml(),
      );
      writeFileSync(
        join(valuesDir, `${WIDGET_STRINGS_XML}.xml`),
        widgetStringsXml(),
      );
      const javaDir = join(
        config.modRequest.platformProjectRoot,
        'app/src/main/java',
        ...packageName.split('.'),
      );
      mkdirSync(javaDir, { recursive: true });
      writeFileSync(
        join(javaDir, 'CashtrixWidgetProvider.java'),
        widgetProviderJava(packageName),
      );
      return config;
    },
  ]);

  return config;
};

export default withCashtrixAppWidget;
