#!/usr/bin/env python3
"""Build all brand raster assets from assets/brand-source.png (stdlib only).

The source is the owner-supplied artwork (squircle on transparency). Every
derived file is regenerated by this script — never hand-edit the outputs:

  assets/icon.png                       1024, artwork on #0A0A0A (store + iOS)
  assets/splash-icon.png                 600, transparent (plugin `contain`)
  assets/android-icon-foreground.png    1024, artwork ~700px (safe zone 66%)
  assets/android-icon-background.png    1024, solid #0A0A0A
  assets/android-icon-monochrome.png    1024, white silhouette from alpha
  assets/favicon.png                      48, artwork on #0A0A0A
  assets/logo-mark.png                   512, square crop, transparent (in-app)

Usage:  python3 scripts/build-brand-assets.py
"""
import binascii
import struct
import zlib

SRC = 'assets/brand-source.png'
BG = (10, 10, 10)  # DESIGN.md canvas
PAD = 8            # transparent padding around the alpha bbox before squaring


def decode_png(path):
    with open(path, 'rb') as f:
        d = f.read()
    assert d[:8] == b'\x89PNG\r\n\x1a\n', 'not a PNG'
    pos, w, h, ctype, idat = 8, 0, 0, 0, b''
    while pos < len(d):
        ln = struct.unpack('>I', d[pos:pos + 4])[0]
        typ = d[pos + 4:pos + 8]
        if typ == b'IHDR':
            w, h, depth, ctype, _, _, inter = struct.unpack(
                '>IIBBBBB', d[pos + 8:pos + 21])
            assert depth == 8 and ctype == 6 and inter == 0, \
                'need 8-bit RGBA non-interlaced'
        elif typ == b'IDAT':
            idat += d[pos + 8:pos + 8 + ln]
        pos += 12 + ln
    raw = zlib.decompress(idat)
    stride = w * 4
    rows, prev, p = [], bytearray(stride), 0
    for _ in range(h):
        f = raw[p]
        p += 1
        cur = bytearray(raw[p:p + stride])
        p += stride
        if f == 1:
            for i in range(4, stride):
                cur[i] = (cur[i] + cur[i - 4]) & 255
        elif f == 2:
            for i in range(stride):
                cur[i] = (cur[i] + prev[i]) & 255
        elif f == 3:
            for i in range(stride):
                a = cur[i - 4] if i >= 4 else 0
                cur[i] = (cur[i] + ((a + prev[i]) >> 1)) & 255
        elif f == 4:
            for i in range(stride):
                a = cur[i - 4] if i >= 4 else 0
                b = prev[i]
                c = prev[i - 4] if i >= 4 else 0
                pp = a + b - c
                pa, pb, pc = abs(pp - a), abs(pp - b), abs(pp - c)
                pr = a if (pa <= pb and pa <= pc) else (b if pb <= pc else c)
                cur[i] = (cur[i] + pr) & 255
        rows.append(bytes(cur))
        prev = cur
    return w, h, b''.join(rows)


def chunk(typ, data):
    return (struct.pack('>I', len(data)) + typ + data +
            struct.pack('>I', binascii.crc32(typ + data) & 0xFFFFFFFF))


def encode_png(w, h, rgba):
    stride = w * 4
    filt = b''.join(b'\x00' + rgba[y * stride:(y + 1) * stride]
                    for y in range(h))
    ihdr = struct.pack('>IIBBBBB', w, h, 8, 6, 0, 0, 0)
    png = (b'\x89PNG\r\n\x1a\n' + chunk(b'IHDR', ihdr) +
           chunk(b'IDAT', zlib.compress(filt, 9)) + chunk(b'IEND', b''))
    return png


def sample(px, w, h, x, y):
    x = min(max(int(x), 0), w - 1)
    y = min(max(int(y), 0), h - 1)
    o = (y * w + x) * 4
    return (px[o], px[o + 1], px[o + 2], px[o + 3])


def resample_square(px, side, dst):
    """Bilinear scale of a square RGBA buffer to dst x dst."""
    out = bytearray(dst * dst * 4)
    s = (side - 1) / max(dst - 1, 1)
    for dy in range(dst):
        sy = dy * s
        y0, y1 = int(sy), min(int(sy) + 1, side - 1)
        fy = sy - y0
        for dx in range(dst):
            sx = dx * s
            x0, x1 = int(sx), min(int(sx) + 1, side - 1)
            fx = sx - x0
            p00 = sample(px, side, side, x0, y0)
            p10 = sample(px, side, side, x1, y0)
            p01 = sample(px, side, side, x0, y1)
            p11 = sample(px, side, side, x1, y1)
            o = (dy * dst + dx) * 4
            for c in range(4):
                v = (p00[c] * (1 - fx) * (1 - fy) +
                     p10[c] * fx * (1 - fy) +
                     p01[c] * (1 - fx) * fy +
                     p11[c] * fx * fy)
                out[o + c] = int(v + 0.5)
    return bytes(out)


def flatten(rgba, bg):
    """Composite RGBA over a solid background (opaque result)."""
    out = bytearray(len(rgba))
    br, bg_, bb = bg
    for i in range(0, len(rgba), 4):
        a = rgba[i + 3] / 255.0
        out[i] = int(rgba[i] * a + br * (1 - a) + 0.5)
        out[i + 1] = int(rgba[i + 1] * a + bg_ * (1 - a) + 0.5)
        out[i + 2] = int(rgba[i + 2] * a + bb * (1 - a) + 0.5)
        out[i + 3] = 255
    return bytes(out)


def silhouette(rgba):
    """White shape from the alpha channel (themed-icon monochrome)."""
    out = bytearray(len(rgba))
    for i in range(0, len(rgba), 4):
        a = rgba[i + 3]
        out[i] = out[i + 1] = out[i + 2] = 255
        out[i + 3] = a
    return bytes(out)


def place_center(canvas_side, art, art_side, target):
    """Center `target`-wide art on a transparent canvas (returns canvas px)."""
    canvas = bytearray(canvas_side * canvas_side * 4)
    off = (canvas_side - target) // 2
    scale = target / art_side
    for dy in range(target):
        sy = min(int(dy / scale), art_side - 1)
        for dx in range(target):
            sx = min(int(dx / scale), art_side - 1)
            s = (sy * art_side + sx) * 4
            dd = ((off + dy) * canvas_side + (off + dx)) * 4
            canvas[dd:dd + 4] = art[s:s + 4]
    return bytes(canvas)


def main():
    w, h, px = decode_png(SRC)
    minx, miny, maxx, maxy = w, h, -1, -1
    for y in range(h):
        base = y * w * 4
        for x in range(w):
            if px[base + x * 4 + 3] > 8:
                minx = min(minx, x)
                maxx = max(maxx, x)
                miny = min(miny, y)
                maxy = max(maxy, y)
    minx = max(minx - PAD, 0)
    miny = max(miny - PAD, 0)
    maxx = min(maxx + PAD, w - 1)
    maxy = min(maxy + PAD, h - 1)
    side = max(maxx - minx + 1, maxy - miny + 1)
    sq = bytearray(side * side * 4)
    ox, oy = (side - (maxx - minx + 1)) // 2, (side - (maxy - miny + 1)) // 2
    for y in range(miny, maxy + 1):
        for x in range(minx, maxx + 1):
            s = (y * w + x) * 4
            dd = ((oy + y - miny) * side + (ox + x - minx)) * 4
            sq[dd:dd + 4] = px[s:s + 4]
    sq = bytes(sq)
    print(f'source {w}x{h}, art square {side}px')

    def write(path, buf, size):
        with open(path, 'wb') as f:
            f.write(encode_png(size, size, buf))
        print(f'wrote {path} {size}x{size}')

    # App icon: artwork ~920px on the canvas colour.
    write('assets/icon.png',
          flatten(place_center(1024, sq, side, 920), BG), 1024)
    # Splash: transparent, plugin `contain`s it on the canvas colour.
    write('assets/splash-icon.png', resample_square(sq, side, 600), 600)
    # Adaptive foreground: artwork inside the 66% safe zone, transparent.
    write('assets/android-icon-foreground.png',
          place_center(1024, sq, side, 700), 1024)
    # Adaptive background: solid canvas.
    solid = bytes(BG + (255,)) * (1024 * 1024)
    write('assets/android-icon-background.png', solid, 1024)
    # Themed-icon monochrome: white silhouette of the artwork.
    write('assets/android-icon-monochrome.png',
          resample_square(silhouette(sq), side, 1024), 1024)
    # Favicon + in-app mark.
    write('assets/favicon.png',
          flatten(resample_square(sq, side, 48), BG), 48)
    write('assets/logo-mark.png', resample_square(sq, side, 512), 512)


if __name__ == '__main__':
    main()
